/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AddGoal {
    }
    interface AppRoot {
    }
}
declare global {
    interface HTMLAddGoalElement extends Components.AddGoal, HTMLStencilElement {
    }
    var HTMLAddGoalElement: {
        prototype: HTMLAddGoalElement;
        new (): HTMLAddGoalElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLElementTagNameMap {
        "add-goal": HTMLAddGoalElement;
        "app-root": HTMLAppRootElement;
    }
}
declare namespace LocalJSX {
    interface AddGoal {
    }
    interface AppRoot {
    }
    interface IntrinsicElements {
        "add-goal": AddGoal;
        "app-root": AppRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "add-goal": LocalJSX.AddGoal & JSXBase.HTMLAttributes<HTMLAddGoalElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
        }
    }
}
