/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AddForm {
        "action": string;
        "description": string;
        "handleCreate": Function;
        "handleUpdate": Function;
        "id": string;
        "isCompleted": boolean;
    }
    interface AppRoot {
    }
    interface DisplayGoals {
        "goals": any[];
        "selectGoal": Function;
    }
}
declare global {
    interface HTMLAddFormElement extends Components.AddForm, HTMLStencilElement {
    }
    var HTMLAddFormElement: {
        prototype: HTMLAddFormElement;
        new (): HTMLAddFormElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLDisplayGoalsElement extends Components.DisplayGoals, HTMLStencilElement {
    }
    var HTMLDisplayGoalsElement: {
        prototype: HTMLDisplayGoalsElement;
        new (): HTMLDisplayGoalsElement;
    };
    interface HTMLElementTagNameMap {
        "add-form": HTMLAddFormElement;
        "app-root": HTMLAppRootElement;
        "display-goals": HTMLDisplayGoalsElement;
    }
}
declare namespace LocalJSX {
    interface AddForm {
        "action"?: string;
        "description"?: string;
        "handleCreate"?: Function;
        "handleUpdate"?: Function;
        "id"?: string;
        "isCompleted"?: boolean;
    }
    interface AppRoot {
    }
    interface DisplayGoals {
        "goals"?: any[];
        "selectGoal"?: Function;
    }
    interface IntrinsicElements {
        "add-form": AddForm;
        "app-root": AppRoot;
        "display-goals": DisplayGoals;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "add-form": LocalJSX.AddForm & JSXBase.HTMLAttributes<HTMLAddFormElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "display-goals": LocalJSX.DisplayGoals & JSXBase.HTMLAttributes<HTMLDisplayGoalsElement>;
        }
    }
}
