/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AddGoal {
    }
    interface AppRoot {
    }
    interface DisplayGoals {
        "goals": any[];
    }
}
declare global {
    interface HTMLAddGoalElement extends Components.AddGoal, HTMLStencilElement {
    }
    var HTMLAddGoalElement: {
        prototype: HTMLAddGoalElement;
        new (): HTMLAddGoalElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLDisplayGoalsElement extends Components.DisplayGoals, HTMLStencilElement {
    }
    var HTMLDisplayGoalsElement: {
        prototype: HTMLDisplayGoalsElement;
        new (): HTMLDisplayGoalsElement;
    };
    interface HTMLElementTagNameMap {
        "add-goal": HTMLAddGoalElement;
        "app-root": HTMLAppRootElement;
        "display-goals": HTMLDisplayGoalsElement;
    }
}
declare namespace LocalJSX {
    interface AddGoal {
    }
    interface AppRoot {
    }
    interface DisplayGoals {
        "goals"?: any[];
    }
    interface IntrinsicElements {
        "add-goal": AddGoal;
        "app-root": AppRoot;
        "display-goals": DisplayGoals;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "add-goal": LocalJSX.AddGoal & JSXBase.HTMLAttributes<HTMLAddGoalElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "display-goals": LocalJSX.DisplayGoals & JSXBase.HTMLAttributes<HTMLDisplayGoalsElement>;
        }
    }
}
